version: "3.7"

services:
  socket-client:
    container_name: socket-client
    build:
      context: ./socket-client
      dockerfile: Dockerfile
    volumes:
      - "./socket-client:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"

  socket-server:
    container_name: socket-server
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - "./:/app"
      - "/app/node_modules"
    ports:
      - "4001:4001"
