{
 "title": "PostGres OIO",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Data Map",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 20, "w": 10, "x": 0, "y": 0 },
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "select teensy_user as metric, count(*) as value,\ncoalesce(nmea_latitude, 90) as latitude, coalesce(nmea_longitude, 0) as longitude, extract(epoch from now())::int as time\nfrom sensors\ngroup by teensy_user, latitude, longitude"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__time(nmea_date),\n  teensy_temperaturesensor\nFROM sensors\nWHERE\n  $__timeFilter(nmea_date)\n"
    }
   ]
  },
  {
   "title": "ORP",
   "type": "graph",
   "gridPos": { "h": 10, "w": 14, "x": 10, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  $__time(nmea_date),\n  teensy_orpsensor\nFROM\n  sensors\nWHERE\n  $__timeFilter(nmea_date)\n"
    }
   ]
  },
  {
   "title": "pHSensor",
   "type": "graph",
   "gridPos": { "h": 11, "w": 23, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(nmea_date),\n  teensy_phsensor\nFROM\n  sensors\nWHERE\n  $__timeFilter(nmea_date)\n"
    }
   ]
  }
 ]
}