# Rename to docker-compose.yml
# Julien Ancelin <julien.ancelin@inra.fr>
version: '3.2'
services:
  web:
    image: nginx:1
    volumes:
      - /home/pirate/geopoppy/etc/nginx.conf:/etc/nginx/nginx.conf
      - /home/pirate/geopoppy/etc/cert.crt:/etc/nginx/cert.crt
      - /home/pirate/geopoppy/etc/cert.key:/etc/nginx/cert.key
      - /home/pirate/geopoppy/var/log/nginx:/var/log/nginx
      - /home/pirate/geopoppy:/srv/lizmap
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
      - lizmap
  lizmap:
#    image: jancelin/geopoppy:rpi_lizmap_client_3.3.0
    image: 3liz/raspberry3-lizmap-web-client:3.3.0
    command: 
      - php-fpm
    environment:
      LIZMAP_WPS_URL: http://wps:8080/
      LIZMAP_CACHESTORAGETYPE: sqlite   
      LIZMAP_CACHEREDISDB: '1'
      LIZMAP_USER: '1010'
      LIZMAP_WMSSERVERURL: http://map:8080/ows/
      LIZMAP_CACHEREDISHOST: redis
      LIZMAP_HOME: /srv/lizmap
      PHP_INI: \r post_max_size = 50M \n
               upload_max_filesize = 10M
    expose:
      - 9000
    volumes:
      - /home/pirate/geopoppy/qgis:/srv/projects
      - /home/pirate/geopoppy/var/lizmap-theme-config:/www/lizmap/var/lizmap-theme-config
      - /home/pirate/geopoppy/var/lizmap-config:/www/lizmap/var/config
      - /home/pirate/geopoppy/var/lizmap-db:/www/lizmap/var/db
      - /home/pirate/geopoppy/www:/www/lizmap/www
      - /home/pirate/geopoppy/var/log/lizmap:/www/lizmap/var/log
      - /home/pirate/geopoppy/qgiscache:/tmp
    restart: unless-stopped
    depends_on:
      - postgis
      - map
      - wps
  map:
    image: 3liz/qgis-raspberry3-server:final-3_4_11-master
    environment:
      PGSERVICEFILE: /srv/etc/pg_service.conf
      QGSRV_CACHE_ROOTDIR: /srv/projects
      QGSRV_SERVER_WORKERS: 4
      QGSRV_CACHE_SIZE: '20'
      QGSRV_LOGGING_LEVEL: DEBUG
      QGSRV_USER: 1000:1000
      ROUTER_HOST: map
      QGSRV_ZMQ_IDENTITY: OWS-SERVER
      QGSRV_ZMQ_INADDR: tcp://*:18080
      QGSRV_ZMQ_MAXQUEUE: 1000
      QGSRV_ZMQ_TIMEOUT: 15000
      LIBGL_DEBUG: verbose glxinfo
    volumes:
      - /home/pirate/geopoppy/qgis:/srv/projects
      - /home/pirate/geopoppy/etc:/srv/etc:ro
      - /home/pirate/geopoppy/qgis/geopoppy/processing/__workdir__:/srv/data
    restart: unless-stopped
    expose:
      - 8080
      - 18080
    ports:
      - 8081:8080
  wps:
    image: 3liz/qgis-raspberry3-wps:final-3_4_11-master
    environment:
      QYWPS_SERVER_PARALLELPROCESSES: '2'
      QYWPS_SERVER_LOGSTORAGE: REDIS
      QYWPS_REDIS_HOST: redis
      QYWPS_PROCESSING_PROVIDERS_MODULE_PATH: /processing
      QYWPS_CACHE_ROOTDIR: /projects
      QYWPS_SERVER_WORKDIR: /srv/data
      QYWPS_USER: 1000
    volumes:
      - /home/pirate/geopoppy/qgis/geopoppy/processing:/processing
      - /home/pirate/geopoppy/qgis:/projects
      - /home/pirate/geopoppy/qgis/geopoppy/processing/__workdir__:/srv/data
      - /home/pirate/geopoppy/qgis/geopoppy/processing/.home:/home/qgis
    ports:
      - 8888:8080
  redis:
    image: redis:4
    volumes:
      - /home/pirate/geopoppy/redis:/data
    restart: always
  cloud:
    image: valentinalexeev/rpi-cloudcmd
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /home/pirate/geopoppy:/mnt/fs
  ftp:
    image: forumi0721alpinearmhf/alpine-armhf-vsftpd:latest
    container_name: ftp
    restart: always
    ports:
      - 20:20
      - 21:21
      - 60000-60099:60000-60099
    volumes:
      - /home/pirate/geopoppy:/data
    environment:
      USER_NAME: geopoppy
      USER_PASSWD: geopoppy
      FTP_SHARE: /data
      FTP_Banner: Geopoppy
    network_mode: host
  postgis:
    image: jancelin/geopoppy:postgres10-2.4-arm32_1
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
#    entrypoint: >
#      bash -c "cp  /home/setup-database.sh / &&
#               /docker-entrypoint.sh"
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=docker
      - POSTGRES_DBNAME=oip
#      - POSTGRES_DUMP=geopoppy.tar
    volumes:
      - /home/pirate/geopoppy/postgresql:/var/lib/postgresql
      - /home/pirate:/home
      - /home/pirate/geopoppy/db_dump:/media

